kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: team1
spec:
  sourceNamespaces:
  - team1-apps
  destinations:
  - namespace: demo-app-team1
    server: https://kubernetes.default.svc
    name: in-cluster