global:
  logging:
    level: debug
  codefresh:
    accountId: 628a80b693a15c0f9c13ab75

  runtime:
    name: side-by-side

    ingress:
      enabled: false

argo-rollouts:
  fullnameOverride: codefresh-argo-rollouts

argo-cd:
  fullnameOverride: codefresh-argo-cd
  crds:
    install: false
  configs:
    cm:
      timeout.reconciliation: 20s
      accounts.admin: apiKey,login
      application.resourceTrackingMethod: annotation+label
    #params: # Awaiting merge of https://github.com/argoproj/argo-cd/pull/14479/files to codefresh fork
    #  application.namespaces: team1-apps
